[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/addons
data_dir = /var/lib/odoo
admin_passwd = admin_secret_token_change_in_production
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_secure_pwd
log_level = info
limit_time_cpu = 600
limit_time_real = 1200
proxy_mode = True
workers = 0
